### ISSUE TITLE
www.hrdevfest.org doesn't route to website 

### ISSUE THREAD

**Issue by troy0820** [RevolutionVA/hrdevfest.github.io#4]
`http://www.hrdevfest.org` doesn't work but `http://hrdevfest.org` does.

Link in README is to `http://www.hrdevfest.org`

**Comment by qwo** [comment]
follow up of enabling https://^ above could be easily solved if routed to CloudFlare dns also.

**Comment by 1kevgriff** [comment]
Fixed.
